### ISSUE TITLE
[BUG] nxalg.all_simple_paths error

### ISSUE THREAD

**Issue by twilmes** [memgraph/mage#107]
**Describe the bug**
Running `nxalg.all_simple_paths` against the attached dataset with the below described arguments crashes MemGraph.

**To Reproduce**
1. `docker run -p 7687:7687 memgraph/memgraph-mage`
2. Copy the vertices and edge files available [here](https://drive.google.com/file/d/186wuiPYs4NZFxRjihrD7m2_NKFi_jLTc/view?usp=sharing_) to the image and load them:
    ```
    LOAD CSV FROM "/tmp/vertices.csv" WITH HEADER AS row
    CREATE (n:Person {id: row.id, name: row.name});

    LOAD CSV FROM "/tmp/edges.csv"  WITH HEADER AS row
    MATCH (p1:Person) where id(p1) = ToInteger(row.id_from)
    with p1, row
    match (p2:Person) where id(p2) = ToInteger(row.id_to)
    CREATE (p1)-[:KNOWS]->(p2)
    ```
3. Run the following query:
    ```
    match p=(p1:Person),(p2:Person)
    where id(p1) = 0 and id(p2) = 5
    CALL nxalg.all_simple_paths(p1, p2, 10) YIELD *
    RETURN paths;
    ```
4. MemGraph crashes and outputs `Fatal Python error: deallocating None`

**Expected behavior**
Query finishes without error.

**Comment by jmatak** [comment]
Hello @twilmes and welcome to the MAGE community !

Thank you for the brief explanation about the issue. I have tried to recreate it and the problem seems to be the scalability of `NetworkX`. The problem lays in its memory inefficiency. It seems to me that you've been trying to fetch all the simple paths with a `cutoff` of length `10`. This on the other hand can be solved just by using a different approach. In Memgraph, you can use path operators to fetch `paths` between nodes. This can be done either by using BSF or DFS sampling. I have written what seems to be the same query as you are trying to run with `NetworkX` below `Memgraph`.
```cypher
MATCH simple_p=(p1:Person)-[*..10]->(p2:Person)
WHERE id(p1) = 0 AND id(p2) = 5
RETURN simple_p;
```
The 10 here is the `cutoff` we are applying in order to reduce the size of these paths.  Furthermore, if you encounter yourself finding `all_shortest_paths`, the solution would be as following:
```cypher
MATCH sp=(p1:Person)-[*bfs]->(p2:Person) 
WHERE id(p1) = 0 AND id(p2) = 5
WITH size(sp) AS bfs_size
MATCH all_shortest_paths=(p1:Person)-[*bfs_size..bfs_size]->(p2:Person) 
WHERE id(p1) = 0 AND id(p2) = 5
RETURN all_shortest_paths;
```

If this doesn't solve your problem, I am here to help further :smile:

**Comment by twilmes** [comment]
Hi @jmatak, thank you and thanks for the explanation and examples. Two questions, would it be possible to handle this gracefully such that the MemGraph process isn't killed if it happens? Second, admittedly more of a general question but do you have any guidance on the typical overhead one would expect when using NetworkX vs. native MemGraph? I'm asking from the standpoint of I was performing a rough resource sizing exercise.

**Comment by jmatak** [comment]
1. Currently, Memgraph is unable to process such behavior without crashing the entire instance, for two reasons. The first reason is that query modules are not run within a **standalone process** and if any **critical error** occurs, especially related to **allocation**, the safest method to handle is to crash the whole process. The second is related to RAM.  If we overload it as in the case of loading in the `NetworkX` graph, the process is killed by **OS**. 

2. Using `NetworkX` would result in **duplication** of graph memory stored in two formats - in `Memgraph` and `NetworkX` graph. There are two different overheads in this example. The first would be the time needed to load the graph into `Python`, and the second one is memory-related - NetworkX is not **memory efficient**, and duplicating the `Memgraph` graph in `NetworkX` results in memory overload.

**Comment by twilmes** [comment]
Makes sense. This may already be in documentation, but if not, it may be good to point out the crash potential just to warn folks who are deploying a multi-user system. Thanks for the sizing info, very helpful.
