### ISSUE TITLE
Add ability to execute CALL on subgraph

### ISSUE THREAD

**Issue by threedliteguy** [memgraph/mage#149]
Add ability to execute logic on a subgraph or projection.

For example, on the sample European roads network, be able to get communities for only the subgraph selected by the below MATCH:

MATCH (a:City{name:'Rome'})-[road:Road*bfs]->(b:City)
 
CALL community_detection.get(
        "length", false,  100000,  1e-06,  0.01
        )
        YIELD community_id, node
        set node.community = community_id
        ;

One possibility is to add nodeProjection and relationshipProjection as CALL parameters:
CALL gds.louvain.write({ nodeProjection: ...,relationshipProjection: , writeProperty: ... {})

**Comment by jmatak** [comment]
Hey @threedliteguy! Thanks for reporting the issue. Memgraph currently doesn't support the projection of patterns to graph but we have some ideas about how to integrate such behavior painlessly.  It's fantastic that you have already proposed some solutions we'll consider using. 

The issue is clear to us, and as soon as we have some output from that side, we'll get back to you. Feel free to ping us if you have more issues, or preferences while using query modules :smile:
