### ISSUE TITLE
[BUG] Crash if wrong number of update args on approximative streaming PageRank

### ISSUE THREAD

**Issue by gitbuda** [memgraph/mage#94]
**Describe the bug**
On `pagerank_online.update`, if the number of arguments is not exactly 4, Memgraph segfaults.

**To Reproduce**
Run `CALL pagerank_online.update({}, {}, {}) YIELD *;` (or any other number/value of arguments).

**Expected behavior**
Memgraph shouldn't crash + the arguments (data) should be correctly processed.

**Additional context**
Tested by directly experimenting on #69.

**Comment by jmatak** [comment]
The issue was having NULL as the default parameter if something is missing. Furthermore to expand, by running this you would still get an error because argument types are list, not sets therefore the correct way to execute would be: 
`CALL pagerank_online.update([],[],[]) YIELD *;`

Since this algorithm and branch are still in development, I will close the issue once the particular feature is merged with the `main` branch. However, consider it fixed because there has been fix committed to this.
